on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint Slim templates for consistent style
        run: bundle exec slim-lint -r github app/views

      - name: Rubocop for ruby files
        run: bundle exec rubocop --require rubocop-rails